### PR TITLE
Support windows

### PR DESCRIPTION
**Pull request by yms2772**
Separating Unix files from Windows files.

### CODE REVIEW

**Comment by Davincible** [comment]
What is the benefit of this exactly? If I see correctly, in the windows file you removed the headless option, thus only non-headless is supported here, which already should work as is.

**Comment by yms2772** [comment]
> What is the benefit of this exactly? If I see correctly, in the windows file you removed the headless option, thus only non-headless is supported here, which already should work as is.

As with #2 , when I "go get" on Windows, I get the error "type *syscall.SysProcAttr has no field or method Pdeathsig". To prevent this, I've separated the files into Windows and Unix.

**Comment by Davincible** [comment]
Ah I see. This quite a heavy workaround, lets first see if we can remove `SysProcAttr`. I copied it over from some other code, perhaps we can test without / find another way

**Comment by themihai** [comment]
The same issue exists on MacOS

**Comment by mihaiav** [comment]
This may be relevant. We may trap the signal using signal.Notify instead of SysProcAttr 
https://github.com/derricw/siggo/pull/11

**Comment by mihaiav** [comment]
I've submitted a PR ( https://github.com/Davincible/chromedp-undetected/pull/7 ) to build both on MacOS and Linux. Unless there is something I'm missing  I believe this PR is toast as it copies unnecessary code that does not work anyway (i.e. Xvfb is not supported on windows ).

**Comment by Davincible** [comment]
@mihaiav @yms2772 I have tried to make a less drastic fix in https://github.com/Davincible/chromedp-undetected/pull/8 could you please check if this fixes it for you?

**Comment by Davincible** [comment]
Closing in favor of #7 

From here on out we can start looking into how to support headless mode on the different platforms. If you have any ideas please let me know or PR!

Thank you for the work and the input @yms2772 @mihaiav

**Pull request closed without merging**
